<script>
  import { onMount } from 'svelte';
  
  let sectionRef;
  let isVisible = $state(false);
  let activeTab = $state('entry');

  const tabs = [
    { id: 'entry', label: 'Entry', icon: '🎟️' },
    { id: 'house', label: 'House Rules', icon: '🏠' },
    { id: 'submission', label: 'Submission', icon: '📤' },
  ];

  const entryRules = [
    'The maximum team size is 5. Any bigger, and we might have to split you up. Solo participation is allowed, but hacking is better with other people!',
    'Due to departmental rules, participants must be students at the University of Cambridge.',
  ];

  const houseRules = [
    { text: 'Please do not bring food into the Intel lab! All food must stay downstairs in the street.', emoji: '🍕' },
    { text: 'You must not bring or consume alcohol at the hackathon.', emoji: '🚫' },
    { text: "We don't recommend it, but you can stay overnight in the lab if you want.", emoji: '😴' },
    { text: 'All participants must follow our Code of Conduct.', emoji: '📜', link: '/code-of-conduct' },
  ];

  const submissionRules = [
    'All work on projects must be done at the hackathon. Using existing open source code is allowed if credited, but the project should be substantially new.',
    'Working on a project and open sourcing it for the sole purpose of using the code in the hackathon is against the spirit of the rules and is not allowed.',
    "AI assistants (Copilot, ChatGPT, etc.) are allowed when writing code, but don't go overboard. For example, using AI assistants as a tool to help you code is fine, but asking one to generate a whole website or the core logic of your application is not allowed. Images generated by external (not part of your project) AI models must be credited, but such use is discouraged.",
    'After hacking finishes, representatives for each track will go around to look at each demo. You are free to look at other projects, as long as one team member is available to present a demo of their project.',
    "If you discover a breaking bug during your demo with a trivial fix, that's okay to rectify. 🐛",
    'Submissions will be made to Devpost.',
  ];

  onMount(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach(entry => {
          if (entry.isIntersecting) {
            isVisible = true;
          }
        });
      },
      { threshold: 0.1 }
    );

    if (sectionRef) observer.observe(sectionRef);

    return () => observer.disconnect();
  });
</script>

<div class="rules-section" bind:this={sectionRef}>
  <div class="content-wrapper" class:visible={isVisible}>
    <div class="section-header">
      <h2 class="section-title">
        <span class="title-icon">📋</span>
        Rules
      </h2>
      <div class="title-underline"></div>
    </div>

    <div class="tabs-container">
      <div class="tabs glass-card">
        {#each tabs as tab}
          <button
            class="tab-button"
            class:active={activeTab === tab.id}
            onclick={() => activeTab = tab.id}
          >
            <span class="tab-icon">{tab.icon}</span>
            <span class="tab-label">{tab.label}</span>
          </button>
        {/each}
        <div class="tab-indicator" style="transform: translateX({tabs.findIndex(t => t.id === activeTab) * 100}%)"></div>
      </div>
    </div>

    <div class="rules-content glass-card">
      {#if activeTab === 'entry'}
        <div class="rules-list">
          {#each entryRules as rule, index}
            <div class="rule-item" style="animation-delay: {index * 0.1}s">
              <div class="rule-number">{index + 1}</div>
              <p class="rule-text">{rule}</p>
            </div>
          {/each}
        </div>
      {:else if activeTab === 'house'}
        <div class="rules-list">
          {#each houseRules as rule, index}
            <div class="rule-item" style="animation-delay: {index * 0.1}s">
              <div class="rule-emoji">{rule.emoji}</div>
              <p class="rule-text">
                {#if rule.link}
                  {rule.text.replace('Code of Conduct', '')}
                  <a href={rule.link} class="theme-hyperlink">Code of Conduct</a>.
                {:else}
                  {rule.text}
                {/if}
              </p>
            </div>
          {/each}
        </div>
      {:else if activeTab === 'submission'}
        <div class="rules-list submission-rules">
          {#each submissionRules as rule, index}
            <div class="rule-item" style="animation-delay: {index * 0.1}s">
              <div class="rule-number">{index + 1}</div>
              <p class="rule-text">
                {#if rule.includes('Devpost')}
                  {rule.replace('Devpost', '')}
                  <a href="https://cam-hack-2025.devpost.com" class="theme-hyperlink">Devpost</a>.
                {:else}
                  {rule}
                {/if}
              </p>
            </div>
          {/each}
        </div>
      {/if}
    </div>
  </div>
</div>

<style>
  .rules-section {
    position: relative;
    padding: 6rem 2rem;
    overflow: hidden;
  }

  .content-wrapper {
    max-width: 900px;
    margin: 0 auto;
    opacity: 0;
    transform: translateY(50px);
    transition: all 0.8s ease-out;
  }

  .content-wrapper.visible {
    opacity: 1;
    transform: translateY(0);
  }

  .section-header {
    text-align: center;
    margin-bottom: 3rem;
  }

  .section-title {
    display: inline-flex;
    align-items: center;
    gap: 0.75rem;
    font-size: clamp(2rem, 5vw, 3rem);
    margin-bottom: 1rem;
  }

  .title-icon {
    font-size: 0.8em;
  }

  .title-underline {
    width: 100px;
    height: 3px;
    background: linear-gradient(90deg, transparent, var(--color-primary), transparent);
    margin: 0 auto;
    border-radius: 2px;
  }

  .tabs-container {
    margin-bottom: 2rem;
  }

  .tabs {
    display: flex;
    position: relative;
    padding: 0.5rem;
    max-width: fit-content;
    margin: 0 auto;
  }

  .tab-button {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.75rem 1.5rem;
    background: transparent;
    border: none;
    color: var(--color-text-muted);
    font-size: 1rem;
    font-weight: 500;
    cursor: pointer;
    position: relative;
    z-index: 1;
    transition: color 0.3s ease;
    white-space: nowrap;
  }

  .tab-button:hover {
    color: var(--color-text-light);
  }

  .tab-button.active {
    color: var(--color-dark);
  }

  .tab-indicator {
    position: absolute;
    top: 0.5rem;
    left: 0.5rem;
    width: calc(33.333% - 0.33rem);
    height: calc(100% - 1rem);
    background: var(--color-primary);
    border-radius: 0.5rem;
    transition: transform 0.3s ease;
  }

  @media (max-width: 640px) {
    .tab-button {
      padding: 0.75rem 1rem;
    }

    .tab-label {
      display: none;
    }

    .tab-icon {
      font-size: 1.25rem;
    }
  }

  .rules-content {
    padding: 2rem;
    min-height: 300px;
  }

  .rules-list {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }

  .rule-item {
    display: flex;
    gap: 1rem;
    align-items: flex-start;
    opacity: 0;
    animation: fade-slide-in 0.5s ease-out forwards;
  }

  @keyframes fade-slide-in {
    from {
      opacity: 0;
      transform: translateX(-20px);
    }
    to {
      opacity: 1;
      transform: translateX(0);
    }
  }

  .rule-number {
    display: flex;
    align-items: center;
    justify-content: center;
    min-width: 32px;
    height: 32px;
    background: rgba(0, 255, 136, 0.1);
    border: 1px solid rgba(0, 255, 136, 0.3);
    border-radius: 50%;
    color: var(--color-primary);
    font-weight: 600;
    font-size: 0.9rem;
  }

  .rule-emoji {
    font-size: 1.5rem;
    min-width: 32px;
    text-align: center;
  }

  .rule-text {
    margin: 0;
    line-height: 1.7;
    color: var(--color-text-light);
  }

  .submission-rules .rule-text {
    font-size: 0.95rem;
  }
</style>
