<script>
  import { onMount } from "svelte";

  let sectionRef;
  let visible = $state(false);

  const sections = [
    {
      title: "Entry",
      icon: "&#128100;",
      rules: [
        "The maximum team size is 5. Any bigger, and we might have to split you up. Solo participation is allowed, but hacking is better with other people!",
        "Due to departmental rules, participants must be students at the University of Cambridge.",
      ],
    },
    {
      title: "House rules",
      icon: "&#127968;",
      rules: [
        "Please do not bring food into the Intel lab! All food must stay downstairs in the street. 🍕",
        "You must not bring or consume alcohol at the hackathon.",
        "We don't recommend it, but you can stay overnight in the lab if you want. 😴",
        {
          text: "All participants must follow our",
          link: { href: "/code-of-conduct", text: "Code of Conduct" },
        },
      ],
    },
    {
      title: "Submission",
      icon: "&#128640;",
      rules: [
        "All work on projects must be done at the hackathon. Using existing open source code is allowed if credited, but the project should be substantially new.",
        "Working on a project and open sourcing it for the sole purpose of using the code in the hackathon is against the spirit of the rules and is not allowed.",
        "AI assistants (Copilot, ChatGPT, etc.) are allowed when writing code, but don't go overboard. For example, using AI assistants as a tool to help you code is fine, but asking one to generate a whole website or the core logic of your application is not allowed. Images generated by external (not part of your project) AI models must be credited, but such use is discouraged.",
        "After hacking finishes, representatives for each track will go around to look at each demo. You are free to look at other projects, as long as one team member is available to present a demo of their project.",
        "If you discover a breaking bug during your demo with a trivial fix, that's okay to rectify. 🐛",
        {
          text: "Submissions will be made to",
          link: { href: "https://cam-hack-2025.devpost.com", text: "Devpost" },
        },
      ],
    },
  ];

  onMount(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            visible = true;
          }
        });
      },
      { threshold: 0.1 }
    );

    if (sectionRef) {
      observer.observe(sectionRef);
    }

    return () => observer.disconnect();
  });
</script>

<div bind:this={sectionRef} class="rules-container">
  <h2 class="section-title" class:visible>
    <span class="title-icon">&#128220;</span>
    Rules
  </h2>

  <div class="rules-grid">
    {#each sections as section, i}
      <div class="rules-card" class:visible style="--delay: {i * 0.2}s">
        <div class="card-header">
          <span class="card-icon">{@html section.icon}</span>
          <h3>{section.title}</h3>
        </div>
        <ul class="rules-list">
          {#each section.rules as rule, j}
            <li style="--item-delay: {j * 0.1}s">
              <span class="rule-bullet"></span>
              {#if typeof rule === "string"}
                <span class="rule-text">{rule}</span>
              {:else}
                <span class="rule-text">
                  {rule.text}
                  <a href={rule.link.href} class="rule-link" target={rule.link.href.startsWith('http') ? '_blank' : undefined}>
                    {rule.link.text}
                  </a>.
                </span>
              {/if}
            </li>
          {/each}
        </ul>
        <div class="card-glow"></div>
      </div>
    {/each}
  </div>
</div>

<style>
  .rules-container {
    max-width: 1280px;
    margin: 0 auto;
    padding: 2rem 1rem;
  }

  .section-title {
    display: flex;
    align-items: center;
    gap: 1rem;
    margin-bottom: 3rem;
    opacity: 0;
    transform: translateY(30px);
    transition:
      opacity 0.8s ease,
      transform 0.8s ease;
  }

  .section-title.visible {
    opacity: 1;
    transform: translateY(0);
  }

  .title-icon {
    font-size: 2.5rem;
  }

  .rules-grid {
    display: grid;
    grid-template-columns: 1fr;
    gap: 2rem;
  }

  @media (min-width: 1024px) {
    .rules-grid {
      grid-template-columns: repeat(3, 1fr);
    }
  }

  .rules-card {
    position: relative;
    padding: 2rem;
    background: rgba(0, 255, 136, 0.02);
    border: 1px solid rgba(0, 255, 136, 0.1);
    border-radius: 20px;
    opacity: 0;
    transform: translateY(40px);
    transition:
      opacity 0.8s ease,
      transform 0.8s ease,
      border-color 0.3s ease,
      background 0.3s ease;
    transition-delay: var(--delay);
    overflow: hidden;
  }

  .rules-card.visible {
    opacity: 1;
    transform: translateY(0);
  }

  .rules-card:hover {
    border-color: rgba(0, 255, 136, 0.3);
    background: rgba(0, 255, 136, 0.05);
  }

  .rules-card:hover .card-glow {
    opacity: 1;
  }

  .card-header {
    display: flex;
    align-items: center;
    gap: 1rem;
    margin-bottom: 1.5rem;
    padding-bottom: 1rem;
    border-bottom: 1px solid rgba(0, 255, 136, 0.1);
  }

  .card-icon {
    font-size: 2rem;
  }

  .card-header h3 {
    margin: 0;
    font-family: "Orbitron", monospace;
  }

  .rules-list {
    list-style: none;
    padding: 0;
    margin: 0;
  }

  .rules-list li {
    display: flex;
    align-items: flex-start;
    gap: 1rem;
    margin-bottom: 1rem;
    opacity: 0;
    transform: translateX(-10px);
    transition:
      opacity 0.5s ease,
      transform 0.5s ease;
  }

  .rules-card.visible .rules-list li {
    opacity: 1;
    transform: translateX(0);
    transition-delay: calc(var(--delay) + var(--item-delay) + 0.3s);
  }

  .rule-bullet {
    flex-shrink: 0;
    width: 8px;
    height: 8px;
    margin-top: 0.5rem;
    background: #00ff88;
    border-radius: 50%;
    box-shadow: 0 0 10px #00ff88;
  }

  .rule-text {
    color: rgba(255, 255, 255, 0.85);
    line-height: 1.6;
  }

  .rule-link {
    color: #00ffcc;
    text-decoration: none;
    transition: all 0.3s ease;
  }

  .rule-link:hover {
    color: #00ff88;
    text-shadow: 0 0 10px rgba(0, 255, 136, 0.5);
  }

  .card-glow {
    position: absolute;
    top: -50%;
    left: -50%;
    width: 200%;
    height: 200%;
    background: radial-gradient(
      circle at center,
      rgba(0, 255, 136, 0.08) 0%,
      transparent 50%
    );
    opacity: 0;
    transition: opacity 0.4s ease;
    pointer-events: none;
  }
</style>
