<div class="rules-container">
  <div class="content-wrapper">
    <h2 class="section-title">
      <span class="title-accent">{"["}</span>
      Rules
      <span class="title-accent">{"]"}</span>
    </h2>
    
    <div class="rules-sections">
      <div class="rule-section">
        <h3 class="subsection-title">
          <span class="section-icon">🎯</span>
          Entry
        </h3>
        <ul class="rule-list">
          <li class="rule-item">
            The maximum team size is 5. Any bigger, and we might have to split you up.
            Solo participation is allowed, but hacking is better with other people!
          </li>
          <li class="rule-item">
            Due to departmental rules, participants must be students at the University
            of Cambridge.
          </li>
        </ul>
      </div>

      <div class="rule-section">
        <h3 class="subsection-title">
          <span class="section-icon">🏠</span>
          House rules
        </h3>
        <ul class="rule-list">
          <li class="rule-item">
            Please do not bring food into the Intel lab! All food must stay downstairs
            in the street. 🍕
          </li>
          <li class="rule-item">
            You must not bring or consume alcohol at the hackathon.
          </li>
          <li class="rule-item">
            We don't recommend it, but you can stay overnight in the lab if you want. 😴
          </li>
          <li class="rule-item">
            All participants must follow our <a
              href="/code-of-conduct"
              class="rule-link">Code of Conduct</a>.
          </li>
        </ul>
      </div>

      <div class="rule-section">
        <h3 class="subsection-title">
          <span class="section-icon">📝</span>
          Submission
        </h3>
        <ul class="rule-list">
          <li class="rule-item">
            All work on projects must be done at the hackathon. Using existing open
            source code is allowed if credited, but the project should be
            substantially new.
          </li>
          <li class="rule-item">
            Working on a project and open sourcing it for the sole purpose of using
            the code in the hackathon is against the spirit of the rules and is not
            allowed.
          </li>
          <li class="rule-item">
            AI assistants (Copilot, ChatGPT, etc.) are allowed when writing code, but
            don't go overboard. For example, using AI assistants as a tool to help you
            code is fine, but asking one to generate a whole website or the core logic
            of your application is not allowed. Images generated by external (not part
            of your project) AI models must be credited, but such use is discouraged.
          </li>
          <li class="rule-item">
            After hacking finishes, representatives for each track will go around to
            look at each demo. You are free to look at other projects, as long as one
            team member is available to present a demo of their project.
          </li>
          <li class="rule-item">
            If you discover a breaking bug during your demo with a trivial fix, that's
            okay to rectify. 🐛
          </li>
          <li class="rule-item">
            Submissions will be made to <a
              href="https://cam-hack-2025.devpost.com"
              class="rule-link">Devpost</a>.
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<style>
  @import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700;900&family=Space+Mono:wght@400;700&display=swap');

  .rules-container {
    padding: 6rem 2rem;
    background: linear-gradient(180deg, rgba(10, 77, 46, 0.2) 0%, rgba(0, 0, 0, 0.9) 100%);
    position: relative;
  }

  .content-wrapper {
    max-width: 1200px;
    margin: 0 auto;
  }

  .section-title {
    font-family: 'Orbitron', sans-serif;
    font-size: clamp(2rem, 5vw, 3.5rem);
    font-weight: 900;
    text-align: center;
    color: #00ff88;
    margin-bottom: 4rem;
    letter-spacing: 0.3rem;
    text-transform: uppercase;
    text-shadow: 0 0 20px rgba(0, 255, 136, 0.5);
  }

  .title-accent {
    color: #88ffb8;
    font-weight: 400;
  }

  .rules-sections {
    display: flex;
    flex-direction: column;
    gap: 3rem;
  }

  .rule-section {
    background: rgba(0, 0, 0, 0.6);
    border: 2px solid rgba(0, 255, 136, 0.3);
    border-radius: 20px;
    padding: 2.5rem;
    transition: all 0.4s cubic-bezier(0.4, 0, 0.2, 1);
  }

  .rule-section:hover {
    border-color: #00ff88;
    box-shadow: 
      0 15px 40px rgba(0, 255, 136, 0.3),
      inset 0 0 20px rgba(0, 255, 136, 0.1);
  }

  .subsection-title {
    font-family: 'Orbitron', sans-serif;
    font-size: clamp(1.5rem, 3vw, 2rem);
    font-weight: 700;
    color: #00ff88;
    margin-bottom: 1.5rem;
    display: flex;
    align-items: center;
    gap: 1rem;
    letter-spacing: 0.2rem;
    text-shadow: 0 0 15px rgba(0, 255, 136, 0.4);
  }

  .section-icon {
    font-size: 2rem;
    filter: drop-shadow(0 0 10px rgba(0, 255, 136, 0.5));
  }

  .rule-list {
    list-style: none;
    padding: 0;
    margin: 0;
  }

  .rule-item {
    font-family: 'Space Mono', monospace;
    font-size: clamp(0.95rem, 1.5vw, 1.1rem);
    line-height: 1.8;
    color: #e0e0e0;
    padding-left: 2rem;
    margin-bottom: 1rem;
    position: relative;
  }

  .rule-item::before {
    content: '▹';
    position: absolute;
    left: 0;
    color: #00ff88;
    font-size: 1.5rem;
    line-height: 1.8rem;
  }

  .rule-item:last-child {
    margin-bottom: 0;
  }

  .rule-link {
    color: #00ff88;
    text-decoration: none;
    font-weight: 700;
    transition: all 0.3s ease;
    text-shadow: 0 0 10px rgba(0, 255, 136, 0.3);
    border-bottom: 2px solid transparent;
  }

  .rule-link:hover {
    color: #88ffb8;
    border-bottom-color: #88ffb8;
    text-shadow: 0 0 20px rgba(0, 255, 136, 0.6);
  }

  @media (max-width: 768px) {
    .rules-container {
      padding: 4rem 1rem;
    }

    .rule-section {
      padding: 2rem;
    }

    .subsection-title {
      font-size: 1.5rem;
    }

    .rule-item {
      padding-left: 1.5rem;
    }
  }
</style>
