<script>
  import { onMount } from "svelte";

  let visible = $state(false);
  let sectionRef;

  const ruleSections = [
    {
      title: "Entry",
      icon: "🎫",
      rules: [
        "The maximum team size is 5. Any bigger, and we might have to split you up. Solo participation is allowed, but hacking is better with other people!",
        "Due to departmental rules, participants must be students at the University of Cambridge.",
      ],
    },
    {
      title: "House rules",
      icon: "🏠",
      rules: [
        "Please do not bring food into the Intel lab! All food must stay downstairs in the street. 🍕",
        "You must not bring or consume alcohol at the hackathon.",
        "We don't recommend it, but you can stay overnight in the lab if you want. 😴",
        "All participants must follow our <a href='/code-of-conduct' class='theme-hyperlink'>Code of Conduct</a>.",
      ],
    },
    {
      title: "Submission",
      icon: "📤",
      rules: [
        "All work on projects must be done at the hackathon. Using existing open source code is allowed if credited, but the project should be substantially new.",
        "Working on a project and open sourcing it for the sole purpose of using the code in the hackathon is against the spirit of the rules and is not allowed.",
        "AI assistants (Copilot, ChatGPT, etc.) are allowed when writing code, but don't go overboard. For example, using AI assistants as a tool to help you code is fine, but asking one to generate a whole website or the core logic of your application is not allowed. Images generated by external (not part of your project) AI models must be credited, but such use is discouraged.",
        "After hacking finishes, representatives for each track will go around to look at each demo. You are free to look at other projects, as long as one team member is available to present a demo of their project.",
        "If you discover a breaking bug during your demo with a trivial fix, that's okay to rectify. 🐛",
        "Submissions will be made to <a href='https://cam-hack-2025.devpost.com' class='theme-hyperlink'>Devpost</a>.",
      ],
    },
  ];

  onMount(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            visible = true;
          }
        });
      },
      { threshold: 0.1 },
    );

    if (sectionRef) {
      observer.observe(sectionRef);
    }

    return () => observer.disconnect();
  });
</script>

<section id="rules" class="section-padding relative" bind:this={sectionRef}>
  <div
    class="pointer-events-none absolute inset-0 bg-gradient-to-b from-black/40 via-transparent to-black/40"
  ></div>

  <div class="relative z-10 mx-auto max-w-5xl">
    <div
      class="mb-16 text-center {visible
        ? 'animate-slide-up opacity-0-initial'
        : 'opacity-0'}"
    >
      <h2 class="text-gradient mb-4">Rules</h2>
    </div>

    <div class="grid grid-cols-1 gap-6 md:grid-cols-3">
      {#each ruleSections as section, i}
        <div
          class="glass-card rounded-2xl border border-zinc-800 p-6 transition-all duration-500 hover:border-emerald-500/30 {visible
            ? 'animate-slide-up opacity-0-initial'
            : 'opacity-0'}"
          style="animation-delay: {0.1 * i + 0.1}s;"
        >
          <div class="mb-4 flex items-center gap-3">
            <span class="text-3xl">{section.icon}</span>
            <h3 class="text-xl text-emerald-400">{section.title}</h3>
          </div>
          <ul class="space-y-3">
            {#each section.rules as rule}
              <li class="flex gap-3 text-sm leading-relaxed text-zinc-300">
                <span class="mt-1.5 shrink-0 text-emerald-500">
                  <svg class="h-3 w-3" fill="currentColor" viewBox="0 0 8 8">
                    <circle cx="4" cy="4" r="3" />
                  </svg>
                </span>
                <span>{@html rule}</span>
              </li>
            {/each}
          </ul>
        </div>
      {/each}
    </div>
  </div>
</section>
