<script>
  import { onMount } from 'svelte';
  
  let visible = false;
  
  onMount(() => {
    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          visible = true;
        }
      });
    }, { threshold: 0.1 });
    
    const section = document.querySelector('#rules');
    if (section) {
      observer.observe(section);
    }
    
    return () => observer.disconnect();
  });
</script>

<div id="rules" class="relative py-20">
  <div class="absolute inset-0 bg-gradient-to-b from-slate-900 via-slate-800 to-slate-900"></div>
  
  <div class="relative z-10 mx-auto max-w-7xl px-4 sm:px-8">
    <h2 class="mb-12 text-center text-5xl font-black text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-cyan-400 drop-shadow-lg">
      Rules
    </h2>
    
    <div class="space-y-8">
      <div
        class="rounded-2xl border border-emerald-500/30 bg-slate-900/50 p-8 backdrop-blur-sm"
        style="animation-delay: 0.2s; opacity: {visible ? 1 : 0};"
        class:animate-slide-in={visible}
      >
        <h3 class="mb-6 text-3xl font-bold text-emerald-300">Entry</h3>
        <ul class="list-disc space-y-3 pl-8 text-lg text-slate-200">
          <li>
            The maximum team size is 5. Any bigger, and we might have to split you up.
            Solo participation is allowed, but hacking is better with other people!
          </li>
          <li>
            Due to departmental rules, participants must be students at the University
            of Cambridge.
          </li>
        </ul>
      </div>
      
      <div
        class="rounded-2xl border border-emerald-500/30 bg-slate-900/50 p-8 backdrop-blur-sm"
        style="animation-delay: 0.4s; opacity: {visible ? 1 : 0};"
        class:animate-slide-in={visible}
      >
        <h3 class="mb-6 text-3xl font-bold text-emerald-300">House rules</h3>
        <ul class="list-disc space-y-3 pl-8 text-lg text-slate-200">
          <li>
            Please do not bring food into the Intel lab! All food must stay downstairs
            in the street. 🍕
          </li>
          <li>You must not bring or consume alcohol at the hackathon.</li>
          <li>
            We don't recommend it, but you can stay overnight in the lab if you want.
            😴
          </li>
          <li>
            All participants must follow our <a
              href="/code-of-conduct"
              class="font-semibold text-emerald-400 transition-colors hover:text-emerald-300"
            >
              Code of Conduct
            </a>.
          </li>
        </ul>
      </div>
      
      <div
        class="rounded-2xl border border-emerald-500/30 bg-slate-900/50 p-8 backdrop-blur-sm"
        style="animation-delay: 0.6s; opacity: {visible ? 1 : 0};"
        class:animate-slide-in={visible}
      >
        <h3 class="mb-6 text-3xl font-bold text-emerald-300">Submission</h3>
        <ul class="list-disc space-y-3 pl-8 text-lg text-slate-200">
          <li>
            All work on projects must be done at the hackathon. Using existing open
            source code is allowed if credited, but the project should be
            substantially new.
          </li>
          <li>
            Working on a project and open sourcing it for the sole purpose of using
            the code in the hackathon is against the spirit of the rules and is not
            allowed.
          </li>
          <li>
            AI assistants (Copilot, ChatGPT, etc.) are allowed when writing code, but
            don't go overboard. For example, using AI assistants as a tool to help you
            code is fine, but asking one to generate a whole website or the core logic
            of your application is not allowed. Images generated by external (not part
            of your project) AI models must be credited, but such use is discouraged.
          </li>
          <li>
            After hacking finishes, representatives for each track will go around to
            look at each demo. You are free to look at other projects, as long as one
            team member is available to present a demo of their project.
          </li>
          <li>
            If you discover a breaking bug during your demo with a trivial fix, that's
            okay to rectify. 🐛
          </li>
          <li>
            Submissions will be made to <a
              href="https://cam-hack-2025.devpost.com"
              class="font-semibold text-emerald-400 transition-colors hover:text-emerald-300"
            >
              Devpost
            </a>.
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
